// This file was auto-generated by ML.NET Model Builder. 


namespace ML_TestPredML.ConsoleApp
{
    public class Program
    {
        static void Main(string[] args)
        {
           
        }
        
    }
}
